name: Deploy AWS Lambda

on:
  push:
    branches: 
      - main

jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run:
          pip install -r requirements.txt

      - name: Run pytest
        run: pytest
        
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC authentication
      contents: read  # Required to check out the repository
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::844216228670:role/github-actions
          aws-region: eu-north-1
      
      - name: Deploy Lambda Function
        uses: aws-actions/aws-lambda-deploy@v1
        with:
          function-name: fvisitorscount-crc
          code-artifacts-dir: ./src
          handler: lambda_function.lambda_handler
          runtime: python3.13
